return {
	{ "stevearc/dressing.nvim", enabled = false },
	{ "rcarriga/nvim-notify", enabled = false },
	{ "folke/noice.nvim", enabled = false },
	-- { "simrat39/symbols-outline.nvim", enabled = false },
	-- { "williamboman/mason.nvim", enabled = false },
	{ "folke/which-key.nvim", enabled = false },
	-- { "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "akinsho/bufferline.nvim", enabled = false },
	{ "folke/flash.nvim", enabled = false },
	-- { "echasnovski/mini.pairs", enabled = false },
	{ "echasnovski/mini.ai", enabled = false },
	{ "nvim-pack/nvim-spectre", enabled = false },
	--{ "MunifTanjim/nui.nvim", enabled = false },
}
